export const reviewData = [
    {
        title:'Web App With Admin Panel',
        desc:"This man is amazing to work with....I know I must have been a difficult customer but he persisted with professionalism and he designed a site that I am super pleased with. Don't hesitate to hire this Freelancer...you will be glad you did.",
        avatar:'https://yt3.googleusercontent.com/v2V0nbWNpg-3lapnunSgunvcX40GukCnSvfob-VpypoQ1Kb6Gh_1CuV-HqzIuO_1lB847XQbAA=s900-c-k-c0x00ffffff-no-rj',
        name:'Sakib',
        rating:3,
    },
    {
        title:'Web Development',
        desc:"This man is amazing to work with....I know I must have been a difficult customer but he persisted with professionalism and he designed a site that I am super pleased with. Don't hesitate to hire this Freelancer...you will be glad you did.",
        avatar:'https://yt3.googleusercontent.com/v2V0nbWNpg-3lapnunSgunvcX40GukCnSvfob-VpypoQ1Kb6Gh_1CuV-HqzIuO_1lB847XQbAA=s900-c-k-c0x00ffffff-no-rj',
        name:'Ron',
        rating:3,
    },
    {
        title:'UI/UX Design',
        desc:"This man is amazing to work with....I know I must have been a difficult customer but he persisted with professionalism and he designed a site that I am super pleased with. Don't hesitate to hire this Freelancer...you will be glad you did.",
        avatar:'https://yt3.googleusercontent.com/v2V0nbWNpg-3lapnunSgunvcX40GukCnSvfob-VpypoQ1Kb6Gh_1CuV-HqzIuO_1lB847XQbAA=s900-c-k-c0x00ffffff-no-rj',
        name:'Sakib',
        rating:3,
    },
    {
        title:'Deployment',
        desc:"This man is amazing to work with....I know I must have been a difficult customer but he persisted with professionalism and he designed a site that I am super pleased with. Don't hesitate to hire this Freelancer...you will be glad you did.",
        avatar:'https://yt3.googleusercontent.com/v2V0nbWNpg-3lapnunSgunvcX40GukCnSvfob-VpypoQ1Kb6Gh_1CuV-HqzIuO_1lB847XQbAA=s900-c-k-c0x00ffffff-no-rj',
        name:'Alif',
        rating:3,
    },
    {
        title:'Back End Developement',
        desc:"This man is amazing to work with....I know I must have been a difficult customer but he persisted with professionalism and he designed a site that I am super pleased with. Don't hesitate to hire this Freelancer...you will be glad you did.",
        avatar:'https://yt3.googleusercontent.com/v2V0nbWNpg-3lapnunSgunvcX40GukCnSvfob-VpypoQ1Kb6Gh_1CuV-HqzIuO_1lB847XQbAA=s900-c-k-c0x00ffffff-no-rj',
        name:'Siam Ahmed',
        rating:3,
    },
    {
        title:'Performence Optimization',
        desc:"This man is amazing to work with....I know I must have been a difficult customer but he persisted with professionalism and he designed a site that I am super pleased with. Don't hesitate to hire this Freelancer...you will be glad you did.",
        avatar:'https://yt3.googleusercontent.com/v2V0nbWNpg-3lapnunSgunvcX40GukCnSvfob-VpypoQ1Kb6Gh_1CuV-HqzIuO_1lB847XQbAA=s900-c-k-c0x00ffffff-no-rj',
        name:'John Doe',
        rating:3,
    },
    {
        title:'Front End Development',
        desc:"This man is amazing to work with....I know I must have been a difficult customer but he persisted with professionalism and he designed a site that I am super pleased with. Don't hesitate to hire this Freelancer...you will be glad you did.",
        avatar:'https://yt3.googleusercontent.com/v2V0nbWNpg-3lapnunSgunvcX40GukCnSvfob-VpypoQ1Kb6Gh_1CuV-HqzIuO_1lB847XQbAA=s900-c-k-c0x00ffffff-no-rj',
        name:'John Doe',
        rating:3,
    },
]